:- dynamic fact/1,class/2.

class(tomRecruiterBot,cognitiveAgent).
class(governor,position).
class(unitedStatesCongress,legislativeOrganization).
class(surprise,emotionalState).
class(unitedKingdomOfGreatBritainAndNorthernIreland,europeanNation).
class(metricTon,unitOfMeasure).
class(yourEmploymentCertificate,certificate).
class(dentist,profession).
class(squareYard,unitOfMeasure).
class(collegeJunior,collegeStudentPosition).
class(maid,unskilledOccupation).
class(fieldOfLaw,fieldOfStudy).
class(unionStatesOfAmerica,geopoliticalArea).
class(secretaryOfTheInterior,governmentSecretary).
class(architecture,fieldOfStudy).
class(tonMass,unitOfMeasure).
class(linguistics,socialScience).
class(goiter,diseaseOrSyndrome).
class(physics,science).
class(changeOfControl,class).
class(privateDetective,profession).
class(policeOfficer,governmentOfficer).
class(kneeling,bodyPosition).
class(doubts,propositionalAttitude).
class(beforeCommonEra,timeInterval).
class(carpenter,occupationalTrade).
class(farmHand,occupationalTrade).
class(biology,science).
class(acre,unitOfMeasure).
class(pope,position).
class(spanishLanguage,naturalLanguage).
class(antisemitism,beliefGroup).
class(horsepower,unitOfMeasure).
class(literature,fieldOfStudy).
class(disapproves,propositionalAttitude).
class(brown,secondaryColor).
class(greekLanguage,spokenHumanLanguage).
class(collegeSophomore,collegeStudentPosition).
class(frenchLanguage,spokenHumanLanguage).
class(physiology,science).
class(greekLanguage,naturalLanguage).
class(attorney,profession).
class(grayColor,secondaryColor).
class(policeOfficer,profession).
class(mugPaintingContest2010,contest).
class(spanishLanguage,spokenHumanLanguage).
class(electronics,fieldOfStudy).
class(frenchLanguage,naturalLanguage).
class(collegeSenior,collegeStudentPosition).
class(page,unitOfMeasure).
class(splitting,bodyPosition).
class(unhappiness,emotionalState).
class(theaterProfession,skilledOccupation).
class(potter,occupationalTrade).
class(republicanParty,politicalParty).
class(emphysema,diseaseOrSyndrome).
class(fever,diseaseOrSyndrome).
class(unitedStatesDepartmentOfState,governmentOrganization).
class(banker,skilledOccupation).
class(coroner,governmentOfficer).
class(dislikes,objectAttitude).
class(clericalSecretary,skilledOccupation).
class(comedian,entertainmentProfession).
class(decade,unitOfMeasure).
class(theology,fieldOfStudy).
class(florida,americanState).
class(russianLanguage,spokenHumanLanguage).
class(engineering,science).
class(unitedStatesDepartmentOfInterior,governmentOrganization).
class(medicalDoctor,profession).
class(cancer,diseaseOrSyndrome).
class(attorneyGeneral,governmentOfficer).
class(century,unitOfMeasure).
class(latinLanguage,naturalLanguage).
class(history,fieldOfStudy).
class(cleric,profession).
class(outdoors,region).
class(happiness,emotionalState).
class(indoors,region).
class(democraticParty,politicalParty).
class(medicalScience,science).
class(accountant,profession).
class(politicalScience,socialScience).
class(roundShape,threeDimensionalFigure).
class(green,secondaryColor).
class(liquorShot,unitOfMeasure).
class(confederateStatesOfAmerica,geopoliticalArea).
class(lieutenantGovernor,position).
class(presidentOfTheUnitedStates,position).
class(mayor,position).
class(purple,secondaryColor).
class(coach,skilledOccupation).
class(yardLength,unitOfMeasure).
class(deacon,religiousPosition).
class(paintingJerrysCupProcess,painting).
class(chemistry,science).
class(jerryTheBot,cognitiveAgent).
class(jerrysCup,drinkingCup).
class(mathematics,fieldOfStudy).
class(latinLanguage,spokenHumanLanguage).
class(commonEra,timeInterval).
class(germanLanguage,spokenHumanLanguage).
class(englishLanguage,naturalLanguage).
class(englishLanguage,spokenHumanLanguage).
class(militaryScience,fieldOfStudy).
class(diarrhea,diseaseOrSyndrome).
class(russianLanguage,naturalLanguage).
class(collegeFreshman,collegeStudentPosition).
class(newsReporter,profession).
class(philosophy,fieldOfStudy).
class(professor,profession).
class(psychology,socialScience).
class(squareMile,unitOfMeasure).
class(pink,secondaryColor).
class(fist,bodyPosition).
class(orangeColor,secondaryColor).
class(tuberculosis,bacterialDisease).
class(naziParty,politicalParty).
class(germanLanguage,naturalLanguage).
class(secretaryOfTheTreasury,governmentSecretary).
class(plumber,occupationalTrade).
class(interiorDesign,fieldOfStudy).
class(cupStillLifeByJerry,paintedPicture).
class(gray,secondaryColor).
class(economics,socialScience).
class(achievingControl,class).
class(handstand,bodyPosition).
class(anthropology,socialScience).


fact(meatOfAnimal(beef,cow)).
fact(meatOfAnimal(pork,pig)).
fact(meatOfAnimal(chickenMeat,chicken)).
fact(serviceProvider(appointing,tomRecruiterAgent)).
fact(property(jerryTheBot,won)).
fact(meatOfAnimal(fishMeat,fish)).
fact(subField(medicalScience,biology)).
fact(subField(electronics,engineering)).
fact(familyName(hal9000,jerryTheBot)).
fact(subField(electronics,physics)).
fact(result(paintingJerrysCupProcess,cupStillLifeByJerry)).
fact(agent(paintingJerrysCupProcess,jerryTheBot)).
fact(initialPart(digitAppendage,limb)).
fact(serviceProvider(expressingApproval,tomRecruiterAgent)).
fact(result(mugPaintingContest2010,won)).
fact(subField(physiology,biology)).
fact(initialPart(animalAnatomicalStructure,animal)).
fact(employs(scottishNationalGalleryOfModernArt,jerryTheBot,titles,hal9000,yourEmploymentCertificate)).
fact(involvedInEvent(mugPaintingContest2010,cupStillLifeByJerry)).
fact(hasSkill(painting,jerryTheBot)).
fact(contestParticipant(mugPaintingContest2010,jerryTheBot)).
fact(represents(cupStillLifeByJerry,jerrysCup)).
