:- use_module(library('linda/server')),
   use_module(library('system')),
   pid(PId),
   linda((Host:Port)-(tell('/tmp/server.addr'),
                      write('\''),
                      write(Host),
                      write('\':'),
                      write(Port-PId),
                      write('.'),
                      told)).