:- dynamic fact/1,class/2.

class(tomRecruiterBot,cognitiveAgent).
class(governor,position).
class(unitedStatesCongress,legislativeOrganization).
class(surprise,emotionalState).
class(brown,secondaryColor).
class(dentist,profession).
class(unitedStatesDepartmentOfInterior,governmentOrganization).
class(soldier,skilledOccupation).
class(fieldOfLaw,fieldOfStudy).
class(unionStatesOfAmerica,geopoliticalArea).
class(secretaryOfTheInterior,governmentSecretary).
class(architecture,fieldOfStudy).
class(linguistics,socialScience).
class(researcher,profession).
class(goiter,diseaseOrSyndrome).
class(physics,science).
class(filmDirector,filmMakingProfession).
class(changeOfControl,class).
class(spanishLanguage,spokenHumanLanguage).
class(privateDetective,profession).
class(policeOfficer,governmentOfficer).
class(decadeDuration,unitOfDuration).
class(kneeling,bodyPosition).
class(doubts,propositionalAttitude).
class(beforeCommonEra,timeInterval).
class(carpenter,occupationalTrade).
class(sailor,skilledOccupation).
class(biology,science).
class(pope,position).
class(paintingJerrysCupProcess,painting).
class(spanishLanguage,naturalLanguage).
class(antisemitism,beliefGroup).
class(literature,fieldOfStudy).
class(teacher,profession).
class(deacon,partTimePosition).
class(greekLanguage,spokenHumanLanguage).
class(farmHand,occupationalTrade).
class(frenchLanguage,spokenHumanLanguage).
class(physiology,science).
class(millenniumDuration,unitOfDuration).
class(greekLanguage,naturalLanguage).
class(acre,unitOfArea).
class(attorney,profession).
class(grayColor,secondaryColor).
class(journalist,profession).
class(metricTon,unitOfMass).
class(policeOfficer,profession).
class(mugPaintingContest2010,contest).
class(page,unitOfInformation).
class(electronics,fieldOfStudy).
class(frenchLanguage,naturalLanguage).
class(collegeSenior,collegeStudentPosition).
class(splitting,bodyPosition).
class(centuryDuration,unitOfDuration).
class(potter,occupationalTrade).
class(republicanParty,politicalParty).
class(emphysema,diseaseOrSyndrome).
class(fever,diseaseOrSyndrome).
class(unitedStatesDepartmentOfState,governmentOrganization).
class(banker,skilledOccupation).
class(coroner,governmentOfficer).
class(dislikes,objectAttitude).
class(clericalSecretary,skilledOccupation).
class(comedian,entertainmentProfession).
class(filmProducer,filmMakingProfession).
class(tonMass,unitOfMass).
class(theaterProfession,skilledOccupation).
class(russianLanguage,spokenHumanLanguage).
class(engineering,science).
class(collegeJunior,collegeStudentPosition).
class(medicalDoctor,profession).
class(cancer,diseaseOrSyndrome).
class(attorneyGeneral,governmentOfficer).
class(yardLength,unitOfLength).
class(latinLanguage,naturalLanguage).
class(history,fieldOfStudy).
class(cleric,profession).
class(unitedKingdom,europeanNation).
class(happiness,emotionalState).
class(indoors,region).
class(democraticParty,politicalParty).
class(treasurer,skilledOccupation).
class(cleric,religiousPosition).
class(collegeSophomore,collegeStudentPosition).
class(medicalScience,science).
class(accountant,profession).
class(disapproves,propositionalAttitude).
class(roundShape,threeDimensionalFigure).
class(green,secondaryColor).
class(outdoors,region).
class(confederateStatesOfAmerica,geopoliticalArea).
class(judge,governmentOfficer).
class(lieutenantGovernor,position).
class(presidentOfTheUnitedStates,position).
class(mayor,position).
class(pharmacist,profession).
class(purple,secondaryColor).
class(coach,skilledOccupation).
class(deacon,religiousPosition).
class(unhappiness,emotionalState).
class(chemistry,science).
class(jerryTheBot,cognitiveAgent).
class(jerrysCup,drinkingCup).
class(mathematics,fieldOfStudy).
class(latinLanguage,spokenHumanLanguage).
class(commonEra,timeInterval).
class(germanLanguage,spokenHumanLanguage).
class(squareMile,unitOfArea).
class(militaryScience,fieldOfStudy).
class(gameReferee,skilledOccupation).
class(politicalScience,socialScience).
class(diarrhea,diseaseOrSyndrome).
class(theology,fieldOfStudy).
class(russianLanguage,naturalLanguage).
class(collegeFreshman,collegeStudentPosition).
class(newsReporter,profession).
class(philosophy,fieldOfStudy).
class(psychology,socialScience).
class(pink,secondaryColor).
class(fist,bodyPosition).
class(orangeColor,secondaryColor).
class(tuberculosis,bacterialDisease).
class(naziParty,politicalParty).
class(germanLanguage,naturalLanguage).
class(secretaryOfTheTreasury,governmentSecretary).
class(publicProsecutor,governmentOfficer).
class(plumber,occupationalTrade).
class(publicDefender,governmentOfficer).
class(interiorDesign,fieldOfStudy).
class(cupStillLifeByJerry,paintedPicture).
class(liquorShot,unitOfVolume).
class(economics,socialScience).
class(squareYard,unitOfArea).
class(handstand,bodyPosition).
class(anthropology,socialScience).


fact(meatOfAnimal(beef,cow)).
fact(subField(electronics,physics)).
fact(initialPart(animalAnatomicalStructure,animal)).
fact(uniqueIdentifier(drinkingCup,'$ORS_HOME/agent_environment/scenarios/sem_matching/SPA/tomRecruiterAgent/html/DrinkingCup.html')).
fact(meatOfAnimal(chickenMeat,chicken)).
fact(serviceProvider(appointing,tomRecruiterAgent)).
fact(initialPart(digitAppendage,limb)).
fact(subField(medicalScience,biology)).
fact(meatOfAnimal(fishMeat,fish)).
fact(meatOfAnimal(pork,pig)).
fact(subField(electronics,engineering)).
fact(serviceProvider(expressingApproval,tomRecruiterAgent)).
fact(subField(physiology,biology)).
fact(uniqueIdentifier(familyName,'$ORS_HOME/agent_environment/scenarios/sem_matching/SPA/tomRecruiterAgent/html/familyName.html')).


%** temp for debugging
fact(hasSkill(painting,jerryTheBot)).
