rule(appointing(Agent),
     [rule1,
      [hasSkill(painting,Agent),not(employs(X,Agent)),familyName(Ln,Agent)],
      [employs(scottishNationalGalleryOfModernArt,Agent),class(yourEmploymentCertificate,certificate),titles(Ln,yourEmploymentCertificate)]
     ]).

% rule(expressingApproval(Agent),
%      [rule2,
%       [class(Agent,cognitiveAgent),class(P,paintedPicture),class(Process,painting),represents(P,Item),agent(Process,Agent),result(Process,P),contestParticipant(mugPaintingContest2010,Agent),involvedInEvent(mugPaintingContest2010,P),result(mugPaintingContest2010,won),property(Agent,won),class(Item,drinkingCup)],
%       [hasSkill(painting,Agent)]
%      ]).

% shortened rule for debugging purposes ...
rule(expressingApproval(Agent),
      [rule2,
       [class(Item,drinkingCup)],
       [hasSkill(painting,Agent)]
      ]).


nonFacts([]).

tasksIPerform([appointing,expressingApproval]).

myFactsList([]).

wait([]).

ask([hasSkill,familyName,represents,agent,result,contestParticipant,involvedInEvent,property,class]).

transitivePredsList([]).

subclass(potOrPan,container).
subclass(grasshopper,insect).
subclass(retina,animalAnatomicalStructure).
subclass(truckTrailer,wagon).
subclass(oil,solution).
subclass(liquefiedPetroleumGas,fossilFuel).
subclass(gunTrigger,engineeringComponent).
subclass(bullet,projectile).
subclass(dramaticPerformance,performance).
subclass(gasolineEngine,internalCombustionEngine).
subclass(financialBill,financialText).
subclass(portrait,paintedPicture).
subclass(creek,freshWaterArea).
subclass(expressingFarewell,expressing).
subclass(thanking,expressingApproval).
subclass(doorway,stationaryArtifact).
subclass(bloodCell,cell).
subclass(oven,heatingDevice).
subclass(college,postSecondarySchool).
subclass(militaryArtifact,artifact).
subclass(missile,selfPoweredDevice).
subclass(poultry,livestock).
subclass(nostril,animalAnatomicalStructure).
subclass(song,musicalComposition).
subclass(frightening,psychologicalProcess).
subclass(tape,attachingDevice).
subclass(governmentBuilding,building).
subclass(ducking,bodyMotion).
subclass(hydrocarbon,organicCompound).
subclass(heatingDevice,device).
subclass(publicSchool,governmentOrganization).
subclass(plantRoot,organ).
subclass(organizationalBoard,organization).
subclass(nationalFlag,flag).
subclass(domesticAnimal,animal).
subclass(legalSummons,ordering).
subclass(seizingProperty,unilateralGetting).
subclass(avocado,fruitOrVegetable).
subclass(bloating,pathologicProcess).
subclass(piano,stringInstrument).
subclass(windInstrument,musicalInstrument).
subclass(reminding,requesting).
subclass(atrophy,pathologicProcess).
subclass(infectiousDisease,diseaseOrSyndrome).
subclass(animalShell,animalAnatomicalStructure).
subclass(newsProgram,broadcastProgram).
subclass(cellulose,plantSubstance).
subclass(horse,hoofedMammal).
subclass(spaceTransportation,transportation).
subclass(tracing,surfaceChange).
subclass(centrifugalMotion,rotating).
subclass(insurancePolicy,certificate).
subclass(alphabeticCharacter,character).
subclass(blueprint,icon).
subclass(partnership,commercialAgent).
subclass(reflectingLight,reflecting).
subclass(mule,hoofedMammal).
subclass(girl,humanChild).
subclass(militaryWaterVehicle,waterVehicle).
subclass(religiousService,demonstrating).
subclass(incendiaryDeviceAttack,violentContest).
subclass(arson,destruction).
subclass(exoskeleton,bodyPart).
subclass(inclining,bodyMotion).
subclass(cylinder,threeDimensionalFigure).
subclass(gameShot,impelling).
subclass(vehicleTire,artifact).
subclass(negotiating,linguisticCommunication).
subclass(femaleCow,cow).
subclass(dressing,putting).
subclass(treeBranch,plantBranch).
subclass(foot,animalAnatomicalStructure).
subclass(christianGospel,text).
subclass(wine,alcoholicBeverage).
subclass(rabbit,rodent).
subclass(jury,groupOfPeople).
subclass(playingCard,contentBearingObject).
subclass(closingEyes,closing).
subclass(lengthening,increasing).
subclass(rat,rodent).
subclass(drawing,surfaceChange).
subclass(humanCorpse,organicObject).
subclass(antigenA,antigen).
subclass(leg,limb).
subclass(compartment,container).
subclass(newTestament,book).
subclass(mailbox,container).
subclass(entertainmentBuilding,building).
subclass(steeringWheel,vehicleController).
subclass(wall,stationaryArtifact).
subclass(radiatingInfrared,radiating).
subclass(bottle,fluidContainer).
subclass(serum,liquidBodySubstance).
subclass(industrialPlant,stationaryArtifact).
subclass(desk,table).
subclass(execution,killing).
subclass(distilledAlcoholicBeverage,alcoholicBeverage).
subclass(wool,fabric).
subclass(militaryInstallation,stationaryArtifact).
subclass(infiltration,joiningAnOrganization).
subclass(camera,device).
subclass(squirrel,rodent).
subclass(religiousBuilding,building).
subclass(compass,contentBearingObject).
subclass(auditoriumSeat,seat).
subclass(carBombing,bombing).
subclass(appointing,declaring).
subclass(civilWar,war).
subclass(stirring,liquidMotion).
subclass(key,securityDevice).
subclass(newspaper,periodical).
subclass(openingEyes,eyeMotion).
subclass(wastebasket,container).
subclass(moth,insect).
subclass(pearFruit,fruitOrVegetable).
subclass(internalCombustionEngine,engine).
subclass(donkey,hoofedMammal).
subclass(broom,brushOrComb).
subclass(nuclearWeapon,radioactiveWeapon).
subclass(trousers,clothing).
subclass(legalSummons,judicialProcess).
subclass(pottery,artifact).
subclass(nuclearWeapon,explosiveDevice).
subclass(diet,plan).
subclass(stringInstrument,musicalInstrument).
subclass(antibody,protein).
subclass(mouse,rodent).
subclass(towel,fabric).
subclass(novel,fictionalText).
subclass(wholesaleStore,agency).
subclass(intestine,animalAnatomicalStructure).
subclass(salesPosition,skilledOccupation).
subclass(rightAngle,twoDimensionalAngle).
subclass(farming,working).
subclass(vehicleBrake,vehicleController).
subclass(chair,seat).
subclass(button,attachingDevice).
subclass(untying,detaching).
subclass(electricMotor,electricDevice).
subclass(apartmentBuilding,residentialBuilding).
subclass(seating,guiding).
subclass(changingClothing,transfer).
subclass(alkaloid,chemicalBase).
subclass(neurosis,psychologicalDysfunction).
subclass(expressingInLanguage,linguisticCommunication).
subclass(documentary,factualText).
subclass(snake,reptile).
subclass(lemonFruit,fruitOrVegetable).
subclass(furniture,artifact).
subclass(lip,animalAnatomicalStructure).
subclass(intestine,bodyVessel).
subclass(publicPark,park).
subclass(barking,radiatingSound).
subclass(accelerating,increasing).
subclass(pitching,gameShot).
subclass(memorizing,learning).
subclass(store,building).
subclass(reflecting,radiating).
subclass(dodging,intentionalProcess).
subclass(windowCovering,artifact).
subclass(fireplace,device).
subclass(militaryTank,artilleryGun).
subclass(fallingAsleep,psychologicalProcess).
subclass(magnetism,radiatingElectromagnetic).
subclass(lock,securityDevice).
subclass(woodArtifact,artifact).
subclass(expressingDisapproval,expressing).
subclass(bumbleBee,bee).
subclass(flower,plantAnatomicalStructure).
subclass(chemicalSalt,compoundSubstance).
subclass(glue,mixture).
subclass(bloodTypeAB,blood).
subclass(inhaling,breathing).
subclass(polygon,closedTwoDimensionalFigure).
subclass(referenceBook,factualText).
subclass(vocalMusic,music).
subclass(profitSharingPlan,pensionPlan).
subclass(educationalProgram,plan).
subclass(formalMeeting,meeting).
subclass(washingDevice,device).
subclass(artSchool,school).
subclass(rocketMissileAttack,bombing).
subclass(collegeStudentPosition,position).
subclass(thunder,radiatingSound).
subclass(militarySurplus,militaryArtifact).
subclass(biting,grabbing).
subclass(collage,artWork).
subclass(renting,financialTransaction).
subclass(placingUnderArrest,capturing).
subclass(letter,factualText).
subclass(aerating,combining).
subclass(meteorite,meteoroid).
subclass(relievingPain,therapeuticProcess).
subclass(audioRecording,text).
subclass(washing,removing).
subclass(opium,biologicallyActiveSubstance).
subclass(politicalCrime,politicalProcess).
subclass(percussionInstrument,musicalInstrument).
subclass(materialHandlingEquipment,device).
subclass(rooster,chicken).
subclass(animalResidence,artifact).
subclass(gamePiece,gameArtifact).
subclass(conjugatedSubstance,compoundSubstance).
subclass(occupationalTrade,manualLabor).
subclass(whiskey,distilledAlcoholicBeverage).
subclass(mirror,artifact).
subclass(magazine,periodical).
subclass(registering,politicalProcess).
subclass(bowing,inclining).
subclass(mailing,transfer).
subclass(pictureFrame,artifact).
subclass(army,militaryService).
subclass(opening,motion).
subclass(report,factualText).
subclass(shield,artifact).
subclass(flour,powder).
subclass(entertainmentCompany,commercialAgent).
subclass(circumision,surgery).
subclass(displayArtifact,artifact).
subclass(welfare,funding).
subclass(holster,container).
subclass(petroleumProduct,oil).
subclass(dress,clothing).
subclass(breast,organ).
subclass(insulin,hormone).
subclass(arrowFigure,icon).
subclass(transportViaRoadVehicle,transportation).
subclass(landing,translocation).
subclass(photograph,icon).
subclass(lyingDown,bodyMotion).
subclass(liquefiedPetroleumGas,refinedPetroleumProduct).
subclass(porch,stationaryArtifact).
subclass(oakWood,woodArtifact).
subclass(butter,dairyProduct).
subclass(alkaloid,biologicallyActiveSubstance).
subclass(entombing,putting).
subclass(coffee,beverage).
subclass(digging,intentionalProcess).
subclass(domesticDog,canine).
subclass(chimney,stationaryArtifact).
subclass(bowing,gesture).
subclass(hat,clothing).
subclass(medicalSchool,graduateSchool).
subclass(gameDie,gamePiece).
subclass(chin,animalAnatomicalStructure).
subclass(honey,animalSubstance).
subclass(battery,electricDevice).
subclass(envelope,container).
subclass(drinkingCup,fluidContainer).
subclass(insuranceCompany,commercialAgent).
subclass(accrediting,declaring).
subclass(commercialUnit,placeOfCommerce).
subclass(steps,stationaryArtifact).
subclass(wingDevice,engineeringComponent).
subclass(receiverDevice,communicationDevice).
subclass(socialParty,meeting).
subclass(anteMeridiem,timeInterval).
subclass(filmMakingProfession,entertainmentProfession).
subclass(tilling,surfaceChange).
subclass(taxonomy,classificationScheme).
subclass(request,sentence).
subclass(commercialShipping,commercialService).
subclass(vehicleLight,lightFixture).
subclass(beer,alcoholicBeverage).
subclass(atrophy,decreasing).
subclass(mine,stationaryArtifact).
subclass(spitting,impelling).
subclass(brain,animalAnatomicalStructure).
subclass(cultivatedLandArea,landArea).
subclass(dieselEngine,internalCombustionEngine).
subclass(rocket,spacecraft).
subclass(fuel,substance).
subclass(constrictorSnake,snake).
subclass(coffin,container).
subclass(dish,holder).
subclass(boarding,translocation).
subclass(chin,bodyPart).
subclass(opticalDevice,device).
subclass(securityUnit,organization).
subclass(bandage,fabric).
subclass(skilledOccupation,position).
subclass(frowning,facialExpression).
subclass(automobile,selfPoweredRoadVehicle).
subclass(tying,attaching).
subclass(paragraph,text).
subclass(wheel,artifact).
subclass(radish,rootVegetable).
subclass(gunPowder,mixture).
subclass(negotiating,contest).
subclass(vein,bloodVessel).
subclass(vocationalSchool,school).
subclass(racing,sport).
subclass(projectileLauncher,weapon).
subclass(urea,organicCompound).
subclass(monument,stationaryArtifact).
subclass(reflexiveProcess,autonomicProcess).
subclass(currencyCoin,currency).
subclass(wireLine,engineeringComponent).
subclass(secondarySchool,school).
subclass(greeting,expressing).
subclass(chimney,device).
subclass(flooding,liquidMotion).
subclass(farm,stationaryArtifact).
subclass(torso,bodyPart).
subclass(filter,device).
subclass(dateFruit,fruitOrVegetable).
subclass(deboarding,translocation).
subclass(vacationing,recreationOrExercise).
subclass(polling,investigating).
subclass(tomb,stationaryArtifact).
subclass(coastGuard,governmentOrganization).
subclass(goose,poultry).
subclass(salineSolution,solution).
subclass(placingUnderArrest,legalAction).
subclass(sentencing,legalDecision).
subclass(statement,sentence).
subclass(composing,contentDevelopment).
subclass(landTransportation,transportation).
subclass(watercolorPicture,paintedPicture).
subclass(bodyJoint,bodyJunction).
subclass(vehicleThrottle,vehicleController).
subclass(baptizing,religiousProcess).
subclass(bloodTypeA,blood).
subclass(rocket,projectile).
subclass(truck,selfPoweredRoadVehicle).
subclass(mediaOrganization,organization).
subclass(pig,livestock).
subclass(cafeteria,restaurant).
subclass(medicine,biologicallyActiveSubstance).
subclass(dutyTax,tax).
subclass(heart,organ).
subclass(burrow,cave).
subclass(application,formText).
subclass(electricalSignalling,signalling).
subclass(novel,book).
subclass(paintedPicture,artWork).
subclass(plantBranch,plantAnatomicalStructure).
subclass(sharing,changeOfPossession).
subclass(referenceBook,book).
subclass(transportationCompany,commercialAgent).
subclass(reflectingLight,radiatingLight).
subclass(postMeridiem,timeInterval).
subclass(smoking,recreationOrExercise).
subclass(kicking,impelling).
subclass(cone,threeDimensionalFigure).
subclass(tube,artifact).
subclass(tractorTrailer,roadVehicle).
subclass(militaryManeuver,maneuver).
subclass(nonprofitOrganization,organization).
subclass(radioBroadcasting,broadcasting).
subclass(cellulose,carbohydrate).
subclass(inclining,motionDownward).
subclass(performance,demonstrating).
subclass(drumming,radiatingSound).
subclass(jumping,bodyMotion).
subclass(audioRecording,contentBearingObject).
subclass(janitor,unskilledOccupation).
subclass(indicating,bodyMotion).
subclass(handle,engineeringComponent).
subclass(sketch,artWork).
subclass(bomb,explosiveDevice).
subclass(chapter,article).
subclass(shotBall,ball).
subclass(brain,organ).
subclass(neck,animalAnatomicalStructure).
subclass(wax,substance).
subclass(proclaiming,lecture).
subclass(ivory,bone).
subclass(spear,weapon).
subclass(wireSpring,wire).
subclass(nectar,plantSubstance).
subclass(vehicleWindow,window).
subclass(antibiotic,biologicallyActiveSubstance).
subclass(orangeFruit,fruitOrVegetable).
subclass(auditorium,building).
subclass(sewageSystem,pipeline).
subclass(elevator,transportationDevice).
subclass(sculpture,artWork).
subclass(bowing,motionDownward).
subclass(fossilFuel,fuel).
subclass(queenInsect,insect).
subclass(selfPoweredRoadVehicle,roadVehicle).
subclass(antelope,hoofedMammal).
subclass(broadcastProgram,series).
subclass(baking,cooking).
subclass(scar,abnormalAnatomicalStructure).
subclass(lung,animalAnatomicalStructure).
subclass(telephoneLine,wireLine).
subclass(shoulder,animalAnatomicalStructure).
subclass(passingABill,declaring).
subclass(drum,percussionInstrument).
subclass(string,artifact).
subclass(stealing,unilateralGetting).
subclass(founding,declaring).
subclass(financialService,commercialService).
subclass(apartmentUnit,singleFamilyResidence).
subclass(hairRemoval,removing).
subclass(neck,bodyPart).
subclass(parkingLot,stationaryArtifact).
subclass(microscope,opticalDevice).
subclass(sportServe,gameShot).
subclass(medicalClinicBuilding,building).
subclass(sword,weapon).
subclass(buffalo,hoofedMammal).
subclass(turningOnDevice,internalChange).
subclass(sunrise,timeInterval).
subclass(hostageTaking,unilateralGetting).
subclass(radiatingVisibleLight,radiatingLight).
subclass(standingUp,motionUpward).
subclass(dormitory,temporaryResidence).
subclass(alcoholicBeverage,beverage).
subclass(chemicalAttack,violentContest).
subclass(motionPictureShot,motionPicture).
subclass(plantRoot,plantAnatomicalStructure).
subclass(gameCall,deciding).
subclass(servicePosition,skilledOccupation).
subclass(nostril,bodyVessel).
subclass(lawn,field).
subclass(writtenCommunication,linguisticCommunication).
subclass(toe,digitAppendage).
subclass(kidnapping,robbing).
subclass(daySchool,school).
subclass(wire,artifact).
subclass(hinge,engineeringComponent).
subclass(votingPoll,stationaryArtifact).
subclass(tilling,intentionalProcess).
subclass(drugStore,retailStore).
subclass(resigning,terminatingEmployment).
subclass(wing,limb).
subclass(maizeGrain,cerealGrain).
subclass(horn,bone).
subclass(standingUp,bodyMotion).
subclass(careOrganization,organization).
subclass(anaconda,constrictorSnake).
subclass(brass,metallicAlloy).
subclass(dayTime,timeInterval).
subclass(lamb,sheep).
subclass(consonant,alphabeticCharacter).
subclass(ladder,artifact).
subclass(lynching,killing).
subclass(gameShot,maneuver).
subclass(stimulant,biologicallyActiveSubstance).
subclass(taxicab,automobile).
subclass(silk,fabric).
subclass(map,icon).
subclass(cityGovernment,government).
subclass(waving,handGesture).
subclass(flour,preparedFood).
subclass(militaryCorps,militaryUnit).
subclass(seat,furniture).
subclass(eye,organ).
subclass(legalAppeal,judicialProcess).
subclass(europeanNation,nation).
subclass(wireLine,wire).
subclass(dramaticPlay,fictionalText).
subclass(finger,digitAppendage).
subclass(funeral,formalMeeting).
subclass(manifold,engineeringComponent).
subclass(criminalAction,intentionalProcess).
subclass(school,educationalOrganization).
subclass(violin,stringInstrument).
subclass(feeding,giving).
subclass(immigrating,translocation).
subclass(seasonOfYear,timeInterval).
subclass(oven,container).
subclass(ball,gamePiece).
subclass(milk,beverage).
subclass(bomb,weapon).
subclass(placingUnderArrest,socialInteraction).
subclass(domesticDog,domesticAnimal).
subclass(shortening,decreasing).
subclass(closet,room).
subclass(coolingDevice,device).
subclass(videoRecording,contentBearingObject).
subclass(explosiveDevice,device).
subclass(blockade,maneuver).
subclass(protozoa,microorganism).
subclass(meteoroid,astronomicalBody).
subclass(library,educationalOrganization).
subclass(circumision,removing).
subclass(cerealGrain,seed).
subclass(legalDismissal,legalDecision).
subclass(working,financialTransaction).
subclass(shirt,clothing).
subclass(rightTriangle,triangle).
subclass(motorcycle,selfPoweredRoadVehicle).
subclass(breast,animalAnatomicalStructure).
subclass(manualLabor,position).
subclass(waterTransportation,transportation).
subclass(animalShell,bodyPart).
subclass(thermometer,measuringDevice).
subclass(horseRiding,carrying).
subclass(cigarOrCigarette,smokingDevice).
subclass(wallpaper,artWork).
subclass(hoistingDevice,materialHandlingEquipment).
subclass(toilet,device).
subclass(securityDevice,device).
subclass(suicideBombing,bombing).
subclass(projectionScreen,communicationDevice).
subclass(holder,device).
subclass(eyeMotion,bodyMotion).
subclass(poultry,bird).
subclass(skeleton,bodyPart).
subclass(telephone,electricDevice).
subclass(publicLibrary,library).
subclass(quadrilateral,polygon).
subclass(financialCompany,commercialAgent).
subclass(trapOrCage,holder).
subclass(explosiveSubstance,substance).
subclass(weekend,timeInterval).
subclass(winking,gesture).
subclass(dreaming,imagining).
subclass(bloating,increasing).
subclass(orthography,procedure).
subclass(boatDeck,artifact).
subclass(dramaticCast,groupOfPeople).
subclass(openingEyes,opening).
subclass(curb,stationaryArtifact).
subclass(pig,hoofedMammal).
subclass(matchDevice,device).
subclass(vehicleController,device).
subclass(jumping,motionUpward).
subclass(flag,icon).
subclass(accelerating,translocation).
subclass(aborting,removing).
subclass(groupOfAnimals,group).
subclass(depressant,biologicallyActiveSubstance).
subclass(fileDevice,device).
subclass(wading,walking).
subclass(answering,stating).
subclass(gameCall,declaring).
subclass(brick,boardOrBlock).
subclass(burying,digging).
subclass(agency,commercialAgent).
subclass(tendon,tissue).
subclass(recoveringFromIllness,organismProcess).
subclass(historicalAccount,narrativeText).
subclass(oilPaint,paint).
subclass(finiteQuantity,quantity).
subclass(table,furniture).
subclass(barn,building).
subclass(knifeAttack,violentContest).
subclass(whip,weapon).
subclass(wheatGrain,cerealGrain).
subclass(vowel,alphabeticCharacter).
subclass(spraying,transfer).
subclass(executiveResidence,permanentResidence).
subclass(shoe,clothing).
subclass(ear,animalAnatomicalStructure).
subclass(militaryService,militaryOrganization).
subclass(automaticGun,gun).
subclass(head,bodyPart).
subclass(humanBaby,humanChild).
subclass(punching,impelling).
subclass(placingUnderArrest,lawEnforcement).
subclass(choreographing,planning).
subclass(placeOfWorship,building).
subclass(graphDiagram,icon).
subclass(humanAdult,human).
subclass(sportsPlay,plan).
subclass(starch,carbohydrate).
subclass(humanYouth,human).
subclass(televisionBroadcasting,broadcasting).
subclass(handgrenadeAttack,bombing).
subclass(sportsGround,stationaryArtifact).
subclass(duck,poultry).
subclass(obliqueAngle,twoDimensionalAngle).
subclass(smokingDevice,device).
subclass(heart,animalAnatomicalStructure).
subclass(clapping,handGesture).
subclass(atmosphericRegion,spaceRegion).
subclass(praying,requesting).
subclass(winking,closingEyes).
subclass(militaryAircraft,militaryVehicle).
subclass(face,bodyPart).
subclass(artPainting,contentDevelopment).
subclass(tellingALie,stating).
subclass(truckTractor,truck).
subclass(humanChild,humanYouth).
subclass(offeringForSale,offering).
subclass(arson,combustion).
subclass(gameArtifact,artifact).
subclass(debating,linguisticCommunication).
subclass(tent,mobileResidence).
subclass(afternoon,dayTime).
subclass(travelContainer,container).
subclass(mortar,weapon).
subclass(takingIll,pathologicProcess).
subclass(legalAward,legalDecision).
subclass(candle,lightFixture).
subclass(ballot,formText).
subclass(submarine,waterVehicle).
subclass(pistol,firearm).
subclass(ossification,organOrTissueProcess).
subclass(nose,organ).
subclass(publicLibrary,governmentOrganization).
subclass(sweat,animalSubstance).
subclass(driveway,roadway).
subclass(missile,projectile).
subclass(escaping,translocation).
subclass(tray,holder).
subclass(artery,bloodVessel).
subclass(reversing,motion).
subclass(kitchen,room).
subclass(facialExpression,gesture).
subclass(tea,beverage).
subclass(busStop,geographicArea).
subclass(popularElection,generalElection).
subclass(truck,cargoVehicle).
subclass(microphone,electricDevice).
subclass(exoskeleton,animalAnatomicalStructure).
subclass(rectangle,quadrilateral).
subclass(commission,organization).
subclass(espionage,politicalProcess).
subclass(gunStock,engineeringComponent).
subclass(causingUnhappiness,process).
subclass(commercialBuilding,building).
subclass(tieClothing,clothing).
subclass(espionage,investigating).
subclass(infiniteQuantity,quantity).
subclass(performanceAct,performance).
subclass(praying,religiousProcess).
subclass(broadcastNetwork,communicationSystem).
subclass(sportsLeague,organization).
subclass(nodding,gesture).
subclass(refrigerator,electricDevice).
subclass(spinalCord,organ).
subclass(anchor,attachingDevice).
subclass(chromatography,separating).
subclass(strangling,grabbing).
subclass(musicText,text).
subclass(atomicGroup,compoundSubstance).
subclass(legalOpinion,argument).
subclass(testForm,formText).
subclass(sheep,domesticAnimal).
subclass(steamEngine,engine).
subclass(lightning,radiating).
subclass(communistParty,politicalParty).
subclass(baking,heating).
subclass(flying,translocation).
subclass(tobacco,floweringPlant).
subclass(fog,waterCloud).
subclass(publicSchool,school).
subclass(layingEggs,organismProcess).
subclass(causingPain,causingUnhappiness).
subclass(sales,working).
subclass(diningRoom,room).
subclass(dough,preparedFood).
subclass(offeringToPurchase,offering).
subclass(transportViaRoadVehicle,landTransportation).
subclass(lens,opticalDevice).
subclass(sinking,falling).
subclass(tail,animalAnatomicalStructure).
subclass(cityBlock,landArea).
subclass(shortStory,article).
subclass(hair,animalAnatomicalStructure).
subclass(signalling,guiding).
subclass(wakingUp,psychologicalProcess).
subclass(radiatingUltraviolet,radiatingElectromagnetic).
subclass(testForm,measuringDevice).
subclass(chemicalAcid,compoundSubstance).
subclass(fireplace,stationaryArtifact).
subclass(writingDevice,device).
subclass(diamond,mineral).
subclass(kidney,animalAnatomicalStructure).
subclass(elephant,herbivore).
subclass(artStudio,workshop).
subclass(window,artifact).
subclass(stairway,stationaryArtifact).
subclass(score,gameShot).
subclass(thyroidHormone,hormone).
subclass(digitAppendage,bodyPart).
subclass(photographicFilm,artifact).
subclass(cholesterol,steroid).
subclass(bloodVessel,bodyVessel).
subclass(taxReturn,formText).
subclass(alcohol,organicCompound).
subclass(chemicalBase,compoundSubstance).
subclass(lawEnforcement,regulatoryProcess).
subclass(oldTestament,book).
subclass(serving,working).
subclass(aminoAcid,organicCompound).
subclass(pork,meat).
subclass(scholarship,funding).
subclass(performanceProgram,factualText).
subclass(telephone,communicationDevice).
subclass(rearWindow,vehicleWindow).
subclass(retailStore,mercantileOrganization).
subclass(spleen,organ).
subclass(gameGoal,gameArtifact).
subclass(windmill,engine).
subclass(drilling,surfaceChange).
subclass(gunBarrel,engineeringComponent).
subclass(shrugging,gesture).
subclass(domesticCat,domesticAnimal).
subclass(passingABill,politicalProcess).
subclass(sheep,hoofedMammal).
subclass(copying,making).
subclass(recreationOrExerciseDevice,device).
subclass(retiring,resigning).
subclass(pigeon,bird).
subclass(motionPictureScene,motionPicture).
subclass(milk,liquidBodySubstance).
subclass(lecture,speaking).
subclass(creek,streamWaterArea).
subclass(fact,statement).
subclass(christianService,religiousService).
subclass(brushOrComb,device).
subclass(missionOrganization,religiousOrganization).
subclass(clamp,attachingDevice).
subclass(skull,bone).
subclass(financialText,report).
subclass(thunder,weatherProcess).
subclass(militaryShip,ship).
subclass(politicalRevolution,politicalProcess).
subclass(televisionReceiver,receiverDevice).
subclass(eyeGlass,opticalDevice).
subclass(broadcasting,disseminating).
subclass(oar,transportationDevice).
subclass(outdoorClothing,clothing).
subclass(passport,license).
subclass(classificationScheme,proposition).
subclass(shrugging,bodyMotion).
subclass(compass,device).
subclass(starving,killing).
subclass(cityDistrict,geopoliticalArea).
subclass(belt,clothing).
subclass(marble,rock).
subclass(beginningOperations,organizationalProcess).
subclass(apron,clothing).
subclass(head,animalAnatomicalStructure).
subclass(retina,organ).
subclass(expressingApproval,expressing).
subclass(lyingDown,motionDownward).
subclass(selfPoweredRoadVehicle,poweredVehicle).
subclass(donkey,livestock).
subclass(university,postSecondarySchool).
subclass(bedroom,room).
subclass(pulmonaryArtery,artery).
subclass(sittingDown,motionDownward).
subclass(square,rectangle).
subclass(calf,cow).
subclass(raping,mating).
subclass(weeping,facialExpression).
subclass(walkingCane,device).
subclass(unionOrganization,organization).
subclass(restaurant,commercialAgent).
subclass(dormitory,residentialBuilding).
subclass(microphone,communicationDevice).
subclass(massaging,touching).
subclass(trembling,bodyMotion).
subclass(fighter,militaryAircraft).
subclass(swimmingPool,fluidContainer).
subclass(smiling,facialExpression).
subclass(bathingDevice,washingDevice).
subclass(mast,artifact).
subclass(tea,preparedFood).
subclass(movingResidence,transfer).
subclass(boy,humanChild).
subclass(safeContainer,container).
subclass(sunlight,radiatingLight).
subclass(educationalFacility,stationaryArtifact).
subclass(whiteBloodCell,bloodCell).
subclass(biopsy,removing).
subclass(box,container).
subclass(arrowProjectile,projectile).
subclass(pensionPlan,financialAccount).
subclass(bronchialDuct,animalAnatomicalStructure).
subclass(ticket,certificate).
subclass(savingsAndLoan,financialCompany).
subclass(circleSector,closedTwoDimensionalFigure).
subclass(legalCharge,legalAction).
subclass(militarySquad,militaryUnit).
subclass(lip,bodyPart).
subclass(kissing,touching).
subclass(animalPoweredDevice,device).
subclass(convoy,collection).
subclass(militaryInfiltration,militaryProcess).
subclass(museum,educationalOrganization).
subclass(touristSite,geographicArea).
subclass(facialHair,hair).
subclass(currencyBill,currency).
subclass(paper,artifact).
subclass(fossilFuel,petroleumProduct).
subclass(knuckle,bodyJoint).
subclass(peeling,removing).
subclass(rug,fabric).
subclass(fence,stationaryArtifact).
subclass(leaving,translocation).
subclass(mortarGun,artilleryGun).
subclass(blanket,fabric).
subclass(tongue,animalAnatomicalStructure).
subclass(policeFacility,building).
subclass(tonalLanguage,spokenHumanLanguage).
subclass(dictionary,referenceBook).
subclass(animalTeam,groupOfAnimals).
subclass(socialScience,science).
subclass(condominiumBuilding,residentialBuilding).
subclass(throat,bodyVessel).
subclass(boardOrBlock,artifact).
subclass(pouring,transfer).
subclass(fallSeason,seasonOfYear).
subclass(vulture,bird).
subclass(artilleryGun,gun).
subclass(pouring,liquidMotion).
subclass(radioactiveWeapon,weaponOfMassDestruction).
subclass(lesion,abnormalAnatomicalStructure).
subclass(mysteryStory,fictionalText).
subclass(cotton,plantAnatomicalStructure).
subclass(harvesting,removing).
subclass(hoof,animalAnatomicalStructure).
subclass(nerveCell,animalAnatomicalStructure).
subclass(photographing,contentDevelopment).
subclass(radiatingSoundUltrasonic,radiatingSound).
subclass(musicRecording,audioRecording).
subclass(cuttingDevice,device).
subclass(ballisticMissile,missile).
subclass(skeleton,animalAnatomicalStructure).
subclass(lyrics,text).
subclass(lung,organ).
subclass(skylight,window).
subclass(closing,motion).
subclass(shoeSole,artifact).
subclass(somersaulting,bodyMotion).
subclass(fullTimePosition,position).
subclass(spinalColumn,animalAnatomicalStructure).
subclass(telegraph,electricDevice).
subclass(socialParty,recreationOrExercise).
subclass(preparedFood,object).
subclass(script,collection).
subclass(stomach,animalAnatomicalStructure).
subclass(battery,powerSource).
subclass(windshield,vehicleWindow).
subclass(inheriting,unilateralGetting).
subclass(lawn,cultivatedLandArea).
subclass(pitching,throwing).
subclass(exhaling,breathing).
subclass(dialysis,separating).
subclass(refrigerator,container).
subclass(lightFixture,device).
subclass(sonar,corpuscularObject).
subclass(anaerobicExerciseDevice,recreationOrExerciseDevice).
subclass(hospitalOrganization,careOrganization).
subclass(coat,outdoorClothing).
subclass(report,article).
subclass(capturing,changeOfControl).
subclass(wood,plantSubstance).
subclass(menstruation,organOrTissueProcess).
subclass(trembling,autonomicProcess).
subclass(laughing,facialExpression).
subclass(antigenB,antigen).
subclass(educationalCourse,educationalProgram).
subclass(bubble,corpuscularObject).
subclass(pillow,artifact).
subclass(performanceStageWing,stationaryArtifact).
subclass(bomber,militaryAircraft).
subclass(gun,weapon).
subclass(spinalColumn,organ).
subclass(watercolorPaint,paint).
subclass(stepping,bodyMotion).
subclass(threatening,committing).
subclass(expressingInLanguage,expressing).
subclass(juniorCollege,postSecondarySchool).
subclass(cottonFabric,fabric).
subclass(bombing,destruction).
subclass(hay,fodder).
subclass(licking,touching).
subclass(taillight,vehicleLight).
subclass(rawFood,object).
subclass(militaryInfiltration,translocation).
subclass(toe,bodyPart).
subclass(headlight,vehicleLight).
subclass(burying,putting).
subclass(radar,electricDevice).
subclass(stove,heatingDevice).
subclass(digitCharacter,character).
subclass(tumor,abnormalAnatomicalStructure).
subclass(ceiling,stationaryArtifact).
subclass(outerSpaceRegion,spaceRegion).
subclass(park,landArea).
subclass(petroleumProduct,miningProduct).
subclass(homeBase,baseballBase).
subclass(feather,bodyPart).
subclass(boy,man).
subclass(bell,percussionInstrument).
subclass(nuclearFamily,familyGroup).
subclass(projectileShell,container).
subclass(highSchool,school).
subclass(alveolus,bodyVessel).
subclass(capillary,bloodVessel).
subclass(alveolus,animalAnatomicalStructure).
subclass(closingContract,committing).
subclass(militaryVehicle,vehicle).
subclass(automobile,passengerVehicle).
subclass(airForce,militaryService).
subclass(regretting,expressingDisapproval).
subclass(tearSubstance,liquidBodySubstance).
subclass(stretching,motion).
subclass(formText,text).
subclass(limb,animalAnatomicalStructure).
subclass(crane,materialHandlingEquipment).
subclass(financing,financialService).
subclass(antenna,communicationDevice).
subclass(incomeTax,tax).
subclass(telegraph,communicationDevice).
subclass(sittingDown,bodyMotion).
subclass(postSecondarySchool,school).
subclass(motorizedRailwayCar,rollingStock).
subclass(divorcing,declaring).
subclass(warehouse,commercialBuilding).
subclass(biologicalConception,organOrTissueProcess).
subclass(chewing,bodyMotion).
subclass(tracing,contentDevelopment).
subclass(girl,woman).
subclass(painting,coloring).
subclass(pulmonaryVein,vein).
subclass(announcement,factualText).
subclass(roadVehicle,landVehicle).
subclass(aerobicExerciseDevice,recreationOrExerciseDevice).
subclass(flyInsect,insect).
subclass(losingConsciousness,psychologicalProcess).
subclass(rifle,firearm).
subclass(order,sentence).
subclass(triangle,polygon).
subclass(door,artifact).
subclass(pencil,writingDevice).
subclass(dough,mixture).
subclass(surfactant,substance).
subclass(proclaiming,declaring).
subclass(spraying,liquidMotion).
subclass(saddle,holder).
subclass(imprisoning,confining).
subclass(tearSubstance,salineSolution).
subclass(catching,touching).
subclass(campground,landArea).
subclass(christianBible,book).
subclass(oxidation,chemicalDecomposition).
subclass(drawing,contentDevelopment).
subclass(serviceOrganization,organization).
subclass(toad,amphibian).
subclass(railroadCompany,transportationCompany).
subclass(bacterialDisease,infectiousDisease).
subclass(massaging,therapeuticProcess).
subclass(screw,attachingDevice).
subclass(rattlesnake,snake).
subclass(lilac,floweringPlant).
subclass(baton,device).
subclass(hotel,temporaryResidence).
subclass(roadTransportationSystem,transitSystem).
subclass(bugle,hornInstrument).
subclass(legalAquittal,legalDecision).
subclass(domesticCat,feline).
subclass(veil,clothing).
subclass(ducking,motionDownward).
subclass(musicalComposition,text).
subclass(maizeGrain,groceryProduce).
subclass(bus,selfPoweredRoadVehicle).
subclass(sportsFacility,stationaryArtifact).
subclass(plantLeaf,plantAnatomicalStructure).
subclass(sock,clothing).
subclass(diluting,putting).
subclass(wood,tissue).
subclass(morning,dayTime).
subclass(diamond,carbon).
subclass(explosion,radiating).
subclass(cloak,clothing).
subclass(privateSchool,school).
subclass(nest,corpuscularObject).
subclass(wireSpring,engineeringComponent).
subclass(handGrenade,bomb).
subclass(tooth,bone).
subclass(workshop,stationaryArtifact).
subclass(dramaticDirecting,guiding).
subclass(motorizedRailwayCar,poweredVehicle).
subclass(militaryReserveForce,militaryOrganization).
subclass(decelerating,translocation).
subclass(acuteAngle,twoDimensionalAngle).
subclass(biopsy,diagnosticProcess).
subclass(communicationSystem,collection).
subclass(arrowIcon,icon).
subclass(peaceKeepingMission,militaryOrganization).
subclass(detergent,mixture).
subclass(ion,pureSubstance).
subclass(willowTree,botanicalTree).
subclass(ducking,intentionalProcess).
subclass(militaryTank,militaryVehicle).
subclass(sphere,threeDimensionalFigure).
subclass(streetcar,electrifiedRailwayCar).
subclass(container,holder).
subclass(cemetery,landArea).
subclass(landVehicle,vehicle).
subclass(plug,artifact).
subclass(arm,limb).
subclass(criminalGang,groupOfPeople).
subclass(hotel,building).
subclass(radioReceiver,receiverDevice).
subclass(condominiumUnit,singleFamilyResidence).
subclass(turningOffDevice,internalChange).
subclass(electronicSignalling,signalling).
subclass(hospitalBuilding,temporaryResidence).
subclass(telephoning,speaking).
subclass(toothbrush,brushOrComb).
subclass(wagon,landVehicle).
subclass(partyPlatform,factualText).
subclass(chestOrCabinet,furniture).
subclass(trespassing,criminalAction).
subclass(watchClock,clock).
subclass(testifying,stating).
subclass(bed,furniture).
subclass(dripping,liquidMotion).
subclass(testament,certificate).
subclass(shelf,artifact).
subclass(turbine,engine).
subclass(bequeathing,unilateralGiving).
subclass(stomach,organ).
subclass(corresponding,linguisticCommunication).
subclass(alcoholicBeverage,depressant).
subclass(psychosis,psychologicalDysfunction).
subclass(spleen,animalAnatomicalStructure).
subclass(installing,putting).
subclass(militaryTank,roadVehicle).
subclass(bee,insect).
subclass(digging,surfaceChange).
subclass(butter,preparedFood).
subclass(pleading,stating).
subclass(ringing,radiatingSound).
subclass(hen,chicken).
subclass(teenager,humanYouth).
subclass(bloodTypeO,blood).
subclass(catching,maneuver).
subclass(chicken,poultry).
subclass(politicalRevolution,violentContest).
subclass(lightning,weatherProcess).
subclass(driversLicense,license).
subclass(field,landArea).
subclass(toe,animalAnatomicalStructure).
subclass(skin,bodyCovering).
subclass(familyBusiness,partnership).
subclass(echoing,radiatingSound).
subclass(centripetalMotion,rotating).
subclass(occupationalTrade,skilledOccupation).
subclass(subway,hole).
subclass(smuggling,transportation).
subclass(ice,water).
subclass(tilling,digging).
subclass(painting,covering).
subclass(interviewing,formalMeeting).
subclass(bag,container).
subclass(radiologicalWeapon,radioactiveWeapon).
subclass(politicalCrime,criminalAction).
subclass(wrist,bodyJoint).
subclass(militaryAircraft,aircraft).
subclass(changeOfControl,achievingControl).
subclass(vehicleWheel,wheel).
subclass(downtown,cityDistrict).
subclass(dodging,bodyMotion).
subclass(takingOff,translocation).
subclass(animalController,device).
subclass(elbow,bodyJoint).
subclass(shipping,transportation).
subclass(science,fieldOfStudy).
subclass(securityAlarm,securityDevice).
subclass(checkpoint,geographicArea).
subclass(religiousService,religiousProcess).
subclass(letterBombAttack,bombing).
subclass(organification,organOrTissueProcess).
subclass(clapping,impacting).
subclass(nonspecificDisease,diseaseOrSyndrome).
subclass(coffee,preparedFood).
subclass(shortStory,fictionalText).
subclass(documentary,motionPicture).
subclass(passCertificate,certificate).
subclass(waterWave,liquidMotion).
subclass(financing,funding).
subclass(powder,substance).
subclass(flower,organ).
subclass(throwing,bodyMotion).
subclass(nuclearWeapon,weapon).
subclass(steeple,stationaryArtifact).
subclass(floor,stationaryArtifact).
subclass(pulling,landTransportation).
subclass(antigen,biologicallyActiveSubstance).
subclass(performanceStage,stationaryArtifact).
subclass(sportsPosition,skilledOccupation).
subclass(teamSport,sport).
subclass(selfPoweredDevice,device).
subclass(engine,transducer).
subclass(marketplace,geographicArea).
subclass(clock,measuringDevice).
subclass(twoDimensionalObject,object).
subclass(radioEmission,radiatingElectromagnetic).
subclass(thumb,finger).
subclass(bronchialDuct,bodyVessel).
subclass(transferringPosition,organizationalProcess).
subclass(medicalClinic,careOrganization).
subclass(vehicleAttack,violentContest).
subclass(ambush,maneuver).
subclass(sandal,shoe).
subclass(brood,groupOfAnimals).
subclass(fluidContainer,container).
subclass(viralDisease,infectiousDisease).
subclass(laboratory,stationaryArtifact).
subclass(sleeve,clothing).
subclass(roof,stationaryArtifact).
subclass(militaryVehicle,militaryPlatform).
subclass(becomingDrunk,psychologicalProcess).
subclass(safeContainer,securityDevice).
subclass(reciting,speaking).
subclass(removingClothing,uncovering).
subclass(ramp,selfConnectedObject).
subclass(leather,fabric).
subclass(gameBoard,gameArtifact).
subclass(mobileResidence,artifact).
subclass(suicideBombing,killing).
subclass(freeAtom,atom).
subclass(nightTime,timeInterval).
subclass(hormoneTSH,hormone).
subclass(playingCard,gameArtifact).
subclass(registering,stating).
subclass(blushing,autonomicProcess).
subclass(hammer,device).
subclass(airTransportation,transportation).
subclass(face,animalAnatomicalStructure).
subclass(commercialBuilding,placeOfCommerce).
subclass(plantBranch,bodyPart).
subclass(militaryInstallation,militaryArtifact).
subclass(arguing,stating).
subclass(soberingUp,psychologicalProcess).
subclass(opium,plantSubstance).
subclass(xRayRadiation,radiating).
subclass(farmBuilding,building).
subclass(revolverGun,pistol).
subclass(religiousPosition,position).
subclass(incendiaryDeviceAttack,combustion).
subclass(pitchersMound,gameArtifact).
subclass(profession,skilledOccupation).
subclass(bloodVessel,animalAnatomicalStructure).
subclass(aerator,device).
subclass(maid,servicePosition).
subclass(businessCompetition,contest).
subclass(baptizing,joiningAnOrganization).
subclass(nervousSystem,organ).
subclass(shoulder,bodyPart).
subclass(question,sentence).
subclass(summerSeason,seasonOfYear).
subclass(televisionReceiver,engineeringComponent).
subclass(sermon,lecture).
subclass(plantLeaf,organ).
subclass(guitar,stringInstrument).
subclass(curtain,windowCovering).
subclass(creek,bodyOfWater).
subclass(mating,organismProcess).
subclass(orchestra,musicalGroup).
subclass(handGesture,gesture).
subclass(fishMeat,meat).
subclass(folding,shapeChange).
subclass(organizationalMerging,organizationalProcess).
subclass(stormFront,atmosphericRegion).
subclass(sewing,attaching).
subclass(spacecraft,vehicle).
subclass(horse,livestock).
subclass(commercialShipping,shipping).
subclass(spaceRegion,region).
subclass(sandwich,preparedFood).
subclass(theaterProfession,entertainmentProfession).
subclass(musicalTone,radiatingSound).
subclass(opera,dramaticPlay).
subclass(subwaySystem,railTransportationSystem).
subclass(militaryFront,geographicArea).
subclass(embassyBuilding,governmentBuilding).
subclass(brandy,distilledAlcoholicBeverage).
subclass(proprietorship,commercialAgent).
subclass(ceasingOperations,organizationalProcess).
subclass(militaryUnit,militaryOrganization).
subclass(riceGrain,cerealGrain).
subclass(explosiveMine,explosiveDevice).
subclass(axle,device).
subclass(soldering,attaching).
subclass(pituitaryGland,gland).
subclass(opium,depressant).
subclass(oilPicture,paintedPicture).
subclass(tremor,rotating).
subclass(sidewalk,stationaryArtifact).
subclass(license,certificate).
subclass(basement,buildingLevel).
subclass(supposition,sentence).
subclass(nuclearFamily,socialUnit).
subclass(laughing,vocalizing).
subclass(militaryShip,militaryWaterVehicle).
subclass(mouth,animalAnatomicalStructure).
subclass(digitAppendage,animalAnatomicalStructure).
subclass(torso,animalAnatomicalStructure).
subclass(herbivore,mammal).
subclass(classroom,room).
subclass(vendingDevice,device).
subclass(partTimePosition,position).
subclass(instrumentalMusic,music).
subclass(syllable,symbolicString).
subclass(electoralCollegeElection,generalElection).
subclass(murder,criminalAction).
subclass(indicating,communication).
subclass(legalConviction,legalDecision).
subclass(ankle,bodyJoint).
subclass(cow,hoofedMammal).
subclass(terroristOrganization,politicalOrganization).
subclass(metallicAlloy,mixture).
subclass(knife,cuttingDevice).
subclass(message,factualText).
subclass(narrativeText,text).
subclass(hand,bodyPart).
subclass(foot,bodyPart).
subclass(eye,animalAnatomicalStructure).
subclass(winterSeason,seasonOfYear).
subclass(legalAppeal,requesting).
subclass(rotor,engineeringComponent).
subclass(organicCompound,compoundSubstance).
subclass(nailDigit,animalAnatomicalStructure).
subclass(bull,cow).
subclass(academicDegree,certificate).
subclass(clapping,radiatingSound).
subclass(modellingPosition,position).
subclass(smokingPipe,smokingDevice).
subclass(birdEgg,egg).
subclass(drumming,demonstrating).
subclass(rubber,bodySubstance).
subclass(hanging,suffocating).
subclass(hornInstrument,musicalInstrument).
subclass(curtain,fabric).
subclass(polyphonicMusic,music).
subclass(switchDevice,engineeringComponent).
subclass(tableware,device).
subclass(aminoAcid,chemicalAcid).
subclass(biography,historicalAccount).
subclass(apple,fruitOrVegetable).
subclass(stretching,lengthening).
subclass(employmentFiring,terminatingEmployment).
subclass(firearm,gun).
subclass(pocket,fabric).
subclass(periodicalPublisher,publisher).
subclass(broadcasting,radioEmission).
subclass(bloodTypeB,blood).
subclass(hijacking,robbing).
subclass(achievingControl,guiding).
subclass(trembling,tremor).
subclass(lecture,demonstrating).
subclass(sugar,carbohydrate).
subclass(stealing,criminalAction).
subclass(sportsTeam,groupOfPeople).
subclass(weaponOfMassDestruction,weapon).
subclass(collar,clothing).
subclass(coconut,fruitOrVegetable).
subclass(industry,collection).
subclass(clothingSuit,collection).
subclass(closingEyes,eyeMotion).
subclass(workerInsect,insect).
subclass(breadOrBiscuit,preparedFood).
subclass(camp,mobileResidence).
subclass(garage,stationaryArtifact).
subclass(trespassing,translocation).
subclass(bathroom,room).
subclass(rowing,waterTransportation).
subclass(courtRoom,room).
subclass(sunset,timeInterval).
subclass(sodiumChloride,chemicalSalt).
subclass(chart,icon).
subclass(stageCoach,wagon).
subclass(fanDevice,coolingDevice).
subclass(laborStriking,organizationalProcess).
subclass(throat,animalAnatomicalStructure).
subclass(nervousSystem,animalAnatomicalStructure).
subclass(tongue,bodyPart).
subclass(chemicalReduction,chemicalSynthesis).
subclass(shoppingMall,mercantileOrganization).
subclass(kidney,organ).
subclass(ear,organ).
subclass(filmMaking,contentDevelopment).
subclass(refrigerator,coolingDevice).
subclass(renting,borrowing).
subclass(drill,cuttingDevice).
subclass(punishing,regulatoryProcess).
subclass(restaurantBuilding,building).
subclass(hoof,bodyPart).
subclass(detergent,surfactant).
subclass(pressureMeasuringDevice,measuringDevice).
subclass(monophonicMusic,music).
subclass(gainingConsciousness,psychologicalProcess).
subclass(hypothalamus,animalAnatomicalStructure).
subclass(nose,animalAnatomicalStructure).
subclass(holidayCard,contentBearingObject).
subclass(eyelid,skin).
subclass(driveComponent,engineeringComponent).
subclass(paint,solution).
subclass(stirring,combining).
subclass(drilling,intentionalProcess).
subclass(securityAlarm,electricDevice).
subclass(owl,bird).
subclass(congratulating,expressingApproval).
subclass(cow,domesticAnimal).
subclass(robbing,stealing).
subclass(screwdriver,device).
subclass(buildingLevel,stationaryArtifact).
subclass(stoning,violentContest).
subclass(graduateSchool,postSecondarySchool).
subclass(glove,clothing).
subclass(washBasin,washingDevice).
subclass(orchestralConducting,guiding).
subclass(explosiveMine,weapon).
subclass(skin,animalAnatomicalStructure).
subclass(carpentry,making).
subclass(aircraft,vehicle).
subclass(resolution,deciding).
subclass(feather,animalAnatomicalStructure).
subclass(dismounting,bodyMotion).
subclass(helicopter,aircraft).
subclass(pancreas,gland).
subclass(label,text).
subclass(tavern,restaurant).
subclass(raping,criminalAction).
subclass(limb,bodyPart).
subclass(redBloodCell,bloodCell).
subclass(bleeding,autonomicProcess).
subclass(dramaticActing,pretending).
subclass(mortarAttack,bombing).
subclass(fallout,powder).
subclass(communicationOrganization,organization).
subclass(founding,organizationalProcess).
subclass(fodder,organicObject).
subclass(cavalryUnit,militaryUnit).
subclass(steroid,biologicallyActiveSubstance).
subclass(officeBuilding,building).
subclass(messaging,transfer).
subclass(thyroidGland,gland).
subclass(chickenMeat,meat).
subclass(beef,meat).
subclass(biologicalSpecies,class).
subclass(unskilledOccupation,manualLabor).
subclass(hand,animalAnatomicalStructure).
subclass(springSeason,seasonOfYear).
subclass(contraceptiveDevice,device).
subclass(ontology,classificationScheme).
subclass(wholesaleStore,mercantileOrganization).
subclass(decelerating,decreasing).
subclass(embracing,touching).
subclass(liver,organ).
subclass(returning,translocation).
subclass(mounting,bodyMotion).
subclass(rotating,motion).
subclass(road,region).
subclass(steroid,organicCompound).
subclass(vandalism,destruction).
subclass(concealing,putting).
subclass(dressingRoom,room).
subclass(governmentOfficer,profession).
subclass(murder,killing).
subclass(glass,mixture).
subclass(nail,attachingDevice).
subclass(causingHappiness,process).
subclass(bathing,washing).
subclass(placeOfCommerce,stationaryArtifact).
subclass(smuggling,criminalAction).
subclass(electricDevice,device).
subclass(throwing,impelling).
subclass(nerveCell,cell).
subclass(rubber,hydrocarbon).
subclass(referenceText,factualText).
subclass(arriving,translocation).
subclass(suicide,killing).
subclass(historicalAccount,factualText).
subclass(pump,transportationDevice).
subclass(rubber,plantSubstance).
subclass(sofa,seat).
subclass(tendon,animalSubstance).
subclass(prison,stationaryArtifact).
subclass(swimmingPool,stationaryArtifact).
subclass(receiverDevice,electricDevice).
subclass(mouth,bodyPart).
subclass(liver,animalAnatomicalStructure).
subclass(artPainting,painting).
subclass(projectile,weapon).
subclass(electricMotor,engine).
subclass(pea,seed).
subclass(gun,projectileLauncher).
subclass(saving,increasing).
subclass(bloodCell,animalAnatomicalStructure).
subclass(grass,floweringPlant).
subclass(knee,bodyJoint).
subclass(chestOrCabinet,container).
subclass(groceryStore,retailStore).
subclass(lawEnforcement,politicalProcess).
subclass(musicalGroup,groupOfPeople).
subclass(antInsect,insect).
subclass(mule,domesticAnimal).
subclass(factory,building).
subclass(fox,canine).
subclass(loadingWeapon,inserting).
subclass(stateGovernment,government).
subclass(composingMusic,contentDevelopment).
subclass(entertainmentProfession,skilledOccupation).
subclass(governmentSecretary,skilledOccupation).
subclass(cholesterol,animalSubstance).
subclass(debating,contest).
subclass(sweeping,removing).
subclass(publisher,commercialAgent).
subclass(bargainSale,offering).
subclass(imagining,psychologicalProcess).
subclass(liquidBodySubstance,bodySubstance).
subclass(focusing,quantityChange).
subclass(steel,metallicAlloy).
subclass(soupStock,preparedFood).
subclass(musicalPerformance,performance).
subclass(hypothalamus,bodyPart).
subclass(gastropod,mollusk).
subclass(suffocating,killing).
